print("Student Registration Form")
print()
first_name = input("Enter first name: ")
last_name = input("Enter last name: ")
year = input("Enter year of birth: ")
print()
print("Welcome "+ first_name + " " + last_name + "!")
print("Your registration is complete.")
print("Your temporary password is " + first_name + "*" + last_name)